# Generated by Django 3.2.7 on 2021-09-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categories_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
